baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My Lab Website'

theme = "hugo-theme-glancy"
themesDir = "../.."

[markup]
  [markup.goldmark]
   [markup.goldmark.renderer]
      unsafe = true